### ISSUE TITLE
Problem with METS file depth

### ISSUE THREAD

**Issue by tboenig** [deutschestextarchiv/tocrify#18]
Hi @wrznr,

I think your program has a problem with the depth of the METS file (part: logical structure). Here are the error messages:
```
Traceback (most recent call last):
  File "/home/matthias/tocrify/env/bin/tocrify", line 10, in <module>
    sys.exit(cli())
  File "/home/matthias/tocrify/env/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/matthias/tocrify/env/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/matthias/tocrify/env/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/matthias/tocrify/env/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/matthias/tocrify/env/lib/python3.6/site-packages/tocrify/scripts/tocrify.py", line 41, in cli
    ingested = hocr_file_hocr[path].ingest_structure(logical)
  File "/home/matthias/tocrify/env/lib/python3.6/site-packages/tocrify/api/hocr.py", line 249, in ingest_structure
    pars[0].set("class", self.mets2hocr.get(logical.type, logical.depth))
  File "/home/matthias/tocrify/env/lib/python3.6/site-packages/tocrify/api/hocr.py", line 59, in get
    return self.map[mets_type][depth]
KeyError: 5
```

**Comment by wrznr** [comment]
The problem here is that the METS-hOCR structural mapping does reach to depth 5. Again, it would be helpful to have ways to reproduce this.

**Comment by tboenig** [comment]
Hi wrznr,
You' re great. That has already helped me. I adjusted the ``yml`` file and added the missing structure depths.
Thank you for the speedy feedback.

**Comment by wrznr** [comment]
I am curious: How did you handle those deep structural elements? Is it `subsubsubsubsubsection`?
