### ISSUE TITLE
Error: list index out of range

### ISSUE THREAD

**Issue by tboenig** [deutschestextarchiv/tocrify#19]
Hi wrznr, 

I don't know what the bugs are.
Here are the error messages 
```
Traceback (most recent call last):
  File "/home/matthias/tocrify/env/bin/tocrify", line 10, in <module>
    sys.exit(cli())
  File "/home/matthias/tocrify/env/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/matthias/tocrify/env/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/matthias/tocrify/env/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/matthias/tocrify/env/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/matthias/tocrify/env/lib/python3.6/site-packages/tocrify/scripts/tocrify.py", line 41, in cli
    ingested = hocr_file_hocr[path].ingest_structure(logical)
  File "/home/matthias/tocrify/env/lib/python3.6/site-packages/tocrify/api/hocr.py", line 245, in ingest_structure
    if len(pars[0]) == len(cmp_lines):
IndexError: list index out of range
```

**Comment by wrznr** [comment]
Pls. provide an example for reproduction of this bug!

**Comment by tboenig** [comment]
Hi wrznr,

Here a link to the METS file: http://brema.suub.uni-bremen.de/dsdk/oai/?verb=GetRecord&metadataPrefix=mets&mode=view&identifier=1856934.
The id number is 453128521. You see that`s an book from Bremen.
Thank you so much for your debugging.

**Comment by wrznr** [comment]
@tboenig Since I do not have access to the hOCR files (anymore), could you please put them somewhere where I can download them?
